image: rust:bookworm

build deb:
  stage: build
  parallel:
    matrix:
      - ARCH: [arm64, amd64]
  tags:
    - saas-linux-small-${ARCH}
  script:
    - cargo install cargo-deb
    - cargo deb -v
  artifacts:
    name: debian package
    paths:
      - target/debian
